name: tests

on:
  push:
    branches: [master, main]
    paths-ignore: ['**.md']
    tags-ignore: ['**']
  pull_request:
    paths-ignore: ['**.md']

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-nomad-manifest:
    name: Validate Nomad manifest
    runs-on: ubuntu-20.04
    steps:
      - uses: gacts/install-nomad@v1

      - uses: actions/checkout@v3

      - run: nomad job validate -var="datadog_api_key=foobar" ./deploy/service.hcl
